##### 简介
Java异常是Java提供的一种识别及响应错误的一致性机制。Java的异常机制可以使程序中异常处理代码和正常业务代码相分离，保证程序代码更加优雅及健壮性。能让程序对于一些不正常的信息清晰的作出 为什么抛出、在哪抛出、抛出什么这一系列的动作。Throwable包含两个子类分别为： Error和Exception。Throwable提供了printStackTrace接口用于获取堆栈跟踪数据等信息。
##### Error(错误)
程序本身无法处理的错误，非程序本身的问题。例如：Virtual MachineError(虚拟机运行错误)、NoClassDefFoundError(类定义错误)、OutOfMemoryError(内存不足错误)、StackOverFlowError(栈溢出错误)，此类错误发生时JVM终止线程。
##### Exception(异常)
程序本身可以捕获并且可以处理的异常。分为两类：运行时异常和编译时异常。
##### RuntimeException(运行时异常)
表示JVM在运行期间可能出现的异常，由Java虚拟机自动抛出并自动捕获。Java编译器不会检查它，也就是说在类中既没有throws抛出异常，也没有try-catch捕捉异常，还是会编译通过，例如：NullPointerException空指针异常、ArrayIndexOutBoundException数组下标越界、ClassCastException类型转换异常、ArithmeticException算术异常。
##### 编译时异常
Exception中除了RuntimeException及其子类之外的异常。Java编译器会检查它，出现这类异常要么throws声明抛出、要么try-catch捕捉处理，否则不能通过编译。例如：ClassNotFundException没有找到指定的异常类、IOExceptionIO流异常等。
##### 受检异常与非受检异常
Java的所有异常可以分为受检异常(checkedException)和非受检异常(uncheckedException)。<br>
受检异常：编译器要求必须处理的异常，当编译器检查到应用中某处可能会有此类异常时，将会提示你处理此异常。要么使用try-catch捕捉处理或者Throws关键字抛出该异常，否则编译不通过。<br>
非受检异常：编译器不会进行检查并且不要求必须处理的异常。也就是说程序中出现此类异常时，即使我们没有try-catch捕捉它，也没有Throws抛出该异常，编译也会通过。该类异常包括运行时异常(RuntimeException)和错误(Error)。
##### Java异常处理
Java通过面向对象的方法进行异常处理，一旦方法抛出异常，系统会根据该异常对象找到合适的异常处理器(Exception Handler)来处理异常。每一个异常都是一个对象，是Throwable类或其子类的实例，当一个方法出现异常后便会抛出一个异常对象，该对象中包含异常信息，调用这个对象的方法便可以捕获这个异常并可以对其处理。Java的异常处理通过五个关键字来实现：try、catch、throw、throws、finally。catch中的return会等finally中的代码执行完之后才会执行,若finally中也包含return语句，finally中的return会覆盖前面的return。

* OutOfMemoryError
内存异常，不是程序能控制的，分配的对象的内存超出了当前最大的堆内存，需要调整堆内存大小（-Xmx）以及优化程序。
* IOException
受检查异常，需要进行捕获。<br>
直接抛出异常：捕获那些知道如何处理的异常，将不知道如何处理的异常继续传递下去,就直接抛出，在方法签名处使用throws关键字声明可能会抛出的异常。

        private static void readFile(String filePath) throws IOException {
            File file = new File(filePath);
            String result;
            BufferedReader reader = new BufferedReader(new FileReader(file));
            while((result = reader.readLine())!=null) {
                System.out.println(result);
            }
            reader.close();
        }
* FileNotFoundException(文件找不到异常)
，如果文件不存在就会抛出这种异常

        private static void readFile(String filePath) {
            try {
                // code
            } catch (FileNotFoundException e) {
                // handle FileNotFoundException
            } catch (IOException e){
                // handle IOException
            }
        }
        同一个catch也可以捕获多种类型异常，用 | 隔开：
        private static void readFile(String filePath) {
            try {
                // code
            } catch (FileNotFoundException | UnknownHostException e) {
                // handle FileNotFoundException or UnknownHostException
            } catch (IOException e){
                // handle IOException
            }
        }
* ClassNotFoundException(类找不到异常)
它是受检查异常，需要进行捕获。是在加载类的时候抛出的，即在类路径下不能加载指定的类。

            public static <T> Class<T> getExistingClass(ClassLoader classLoader, String className) {
              try {
                 return (Class<T>) Class.forName(className, true, classLoader);
              }
              catch (ClassNotFoundException e) {
                 return null;
              }
            }
        
           private static void readFile(String filePath) throws MyException {
            File file = new File(filePath);
            String result;
            BufferedReader reader = null;
            try {
                reader = new BufferedReader(new FileReader(file));
                while((result = reader.readLine())!=null) {
                    System.out.println(result);
                }
            } catch (IOException e) {
                throw new XXXException("XXXX");
            } finally {
                System.out.println("readFile method finally block.");
                if (null != reader) {
                    try {
                        reader.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }
        }
 读取文件时若发生异常，代码会进入 catch 代码块，之后进入 finally 代码块；若读取文件时未发生异常，则会跳过 catch 代码块直接进入 finally 代码块。所以无论代码中是否发生异常，fianlly 中的代码都会执行。
* ClassCastException(类转换异常)
这是运行时异常，不需要手工捕获，将一个不是该类的实例转换成这个类就会抛出这个异常。
如将一个数字强制转换成字符串就会报这个异常：

    Object x = new Integer(0);
    System.out.println((String)x);

* NoSuchMethodException(没有这个方法异常)
是受检查异常，需要进行捕获。一般发生在反射调用方法的时候，如：

    public Method getMethod(String name, Class<?>... parameterTypes)
        throws NoSuchMethodException, SecurityException {
        checkMemberAccess(Member.PUBLIC, Reflection.getCallerClass(), true);
        Method method = getMethod0(name, parameterTypes, true);
        if (method == null) {
            throw new NoSuchMethodException(getName() + "." + name + argumentTypesToString(parameterTypes));
        }
        return method;
    }

* IndexOutOfBoundsException(索引越界异常)
当操作一个字符串或者数组的时候经常遇到的异常。
* ArithmeticException(算术异常)
发生在数字的算术运算时的异常，如一个数字除以0就会报这个错。double n = 3 / 0;

    public static Timestamp from(Instant instant) {
        try {
            Timestamp stamp = new Timestamp(instant.getEpochSecond() * MILLIS_PER_SECOND);
            stamp.nanos = instant.getNano();
            return stamp;
        } catch (ArithmeticException ex) {
            throw new IllegalArgumentException(ex);
        }
    }
* SQLException
SQL异常，发生在操作数据库时的异常。
##### final、finally、finalize区别
`final`是修饰符，修饰类，此类不能被继承，修饰方法和变量，则表示此方法和此变量不能在被改变，`finally`是try-catch-finally 最后一部分，表示不论发生任何情况都会执行，finalize()是Object中的方法，当垃圾回收器将要回收对象所占内存之前被调用，即当一个对象被虚拟机宣告死亡时会先调用它finalize()方法，让此对象处理它生前的最后事情（这个对象可以趁这个时机挣脱死亡的命运）。
##### Error 和 Exception 区别
Error 类型的错误通常为虚拟机相关错误，如系统崩溃，内存不足，堆栈溢出等，编译器不会对这类错误进行检测，JAVA应用程序也不对这类错误进行捕获，一旦这类错误发生，通常应用程序会被终止，仅靠应用程序本身无法恢复；<br>
Exception 类的错误是可以在应用程序中进行捕获并处理的，通常遇到这种错误，应对其进行处理，使应用程序可以继续正常运行。

##### 运行时异常和一般异常(受检异常)区别
运行时异常包括 RuntimeException 类及其子类，表示 JVM 在运行期间可能出现的异常。Java 编译器不会检查运行时异常。<br>
受检异常是Exception 中除 RuntimeException 及其子类之外的异常。Java 编译器会检查受检异常。<br>
RuntimeException异常和受检异常之间的区别：是否强制要求调用者必须处理此异常，如果强制要求调用者必须进行处理，那么就使用受检异常，否则就选择非受检异常(RuntimeException)。

##### JVM 是如何处理异常的
在一个方法中如果发生异常，这个方法会创建一个异常对象，并转交给 JVM，该异常对象包含异常名称，异常描述以及异常发生时应用程序的状态。创建异常对象并转交给 JVM 的过程称为抛出异常。可能有一系列的方法调用，最终才进入抛出异常的方法，这一系列方法调用的有序列表叫做调用栈。<br>
JVM 会顺着调用栈去查找看是否有可以处理异常的代码，如果有，则调用异常处理代码。当 JVM 发现可以处理异常的代码时，会把发生的异常传递给它。如果 JVM 没有找到可以处理该异常的代码块，JVM 就会将该异常转交给默认的异常处理器（默认处理器为 JVM 的一部分），默认异常处理器打印出异常信息并终止应用程序。

##### throw 和 throws 的区别
Java 中的异常处理除了包括捕获异常和处理异常之外，还包括声明异常和拋出异常，可以通过 throws 关键字在方法上声明该方法要拋出的异常，或者在方法内部通过 throw 拋出异常对象。<br>
throws 关键字和 throw 关键字在使用上的几点区别如下：<br>
throw 关键字用在方法内部，只能用于抛出一种异常，用来抛出方法或代码块中的异常，受查异常和非受查异常都可以被抛出。<br>
throws 关键字用在方法声明上，可以抛出多个异常，用来标识该方法可能抛出的异常列表。一个方法用 throws 标识了可能抛出的异常列表，调用该方法的方法中必须包含可处理异常的代码，否则也要在方法签名中用 throws 关键字声明相应的异常。
##### final、finally、finalize区别
final可以修饰类、变量、方法，修饰类表示该类不能被继承、修饰方法表示该方法不能被重写、修饰变量表示该变量是一个常量不能被重新赋值。<br>
finally一般作用在try-catch代码块中，在处理异常的时候，通常我们将一定要执行的代码方法finally代码块中，表示不管是否出现异常，该代码块都会执行，一般用来存放一些关闭资源的代码。<br>
finalize是一个方法，属于Object类的一个方法，而Object类是所有类的父类，Java 中允许使用 finalize()方法在垃圾收集器将对象从内存中清除出去之前做必要的清理工作。<br>
##### NoClassDefFoundError 和 ClassNotFoundException 区别
NoClassDefFoundError 是一个 Error 类型的异常，是由 JVM 引起的，不应该尝试捕获这个异常。引起该异常的原因是 JVM 或 ClassLoader 尝试加载某类时在内存中找不到该类的定义，该动作发生在运行期间，即编译时该类存在，但是在运行时却找不到了，可能是变异后被删除了等原因导致；<br>
ClassNotFoundException 是一个受查异常，需要显式地使用 try-catch 对其进行捕获和处理，或在方法签名中用 throws 关键字进行声明。当使用 Class.forName, ClassLoader.loadClass 或 ClassLoader.findSystemClass 动态加载类到内存的时候，通过传入的类路径参数没有找到该类，就会抛出该异常；另一种抛出该异常的可能原因是某个类已经由一个类加载器加载至内存中，另一个加载器又尝试去加载它。
##### try-catch-finally 中哪个部分可以省略
答：catch 可以省略，try只适合处理运行时异常，try+catch适合处理运行时异常+普通异常。也就是说，如果你只用try去处理普通异常却不加以catch处理，编译是通不过的，因为编译器硬性规定，普通异常如果选择捕获，则必须用catch显示声明以便进一步处理。而运行时异常在编译时没有如此规定，所以catch可以省略，你加上catch编译器也觉得无可厚非。<br>

理论上，编译器看任何代码都不顺眼，都觉得可能有潜在的问题，所以你即使对所有代码加上try，代码在运行期时也只不过是在正常运行的基础上加一层皮。但是你一旦对一段代码加上try，就等于显示地承诺编译器，对这段代码可能抛出的异常进行捕获而非向上抛出处理。如果是普通异常，编译器要求必须用catch捕获以便进一步处理；如果运行时异常，捕获然后丢弃并且+finally扫尾处理，或者加上catch捕获以便进一步处理。

至于加上finally，则是在不管有没捕获异常，都要进行的“扫尾”处理。

##### try-catch-finally 中，如果 catch 中 return 了，finally 还会执行吗？
会执行，在 return 前执行。<br>

注意：在 finally 中改变返回值的做法是不好的，因为如果存在 finally 代码块，try中的 return 语句不会立马返回调用者，而是记录下返回值待 finally 代码块执行完毕之后再向调用者返回其值，然后如果在 finally 中修改了返回值，就会返回修改后的值。显然，在 finally 中返回或者修改返回值会对程序造成很大的困扰，C#中直接用编译错误的方式来阻止程序员干这种龌龊的事情，Java 中也可以通过提升编译器的语法检查级别来产生警告或错误。

                代码示例1：
                public static int getInt() {
                    int a = 10;
                    try {
                        System.out.println(a / 0);
                        a = 20;
                    } catch (ArithmeticException e) {
                        a = 30;
                        return a;
                        /*
                         * return a 在程序执行到这一步的时候，这里不是return a 而是 return 30；这个返回路径就形成了
                         * 但是呢，它发现后面还有finally，所以继续执行finally的内容，a=40
                         * 再次回到以前的路径,继续走return 30，形成返回路径之后，这里的a就不是a变量了，而是常量30
                         */
                    } finally {
                        a = 40;
                    }
                 return a;
                }
                执行结果：30

                代码示例2：
                public static int getInt() {
                    int a = 10;
                    try {
                        System.out.println(a / 0);
                        a = 20;
                    } catch (ArithmeticException e) {
                        a = 30;
                        return a;
                    } finally {
                        a = 40;
                        //如果这样，就又重新形成了一条返回路径，由于只能通过1个return返回，所以这里直接返回40
                        return a; 
                    }
                }
                执行结果：40

##### 类 ExampleA 继承 Exception，类 ExampleB 继承ExampleA。

                有如下代码片断：

                try {
                 throw new ExampleB("b")
                } catch（ExampleA e）{
                 System.out.println("ExampleA");
                } catch（Exception e）{
                 System.out.println("Exception");
                }
请问执行此段代码的输出是什么<br>
输出：ExampleA。（根据里氏代换原则[能使用父类型的地方一定能使用子类型]，抓取 ExampleA 类型异常的 catch 块能够抓住 try 块中抛出的 ExampleB 类型的异常）

面试题 - 说出下面代码的运行结果。

                class Annoyance extends Exception {
                }
                class Sneeze extends Annoyance {
                }
                class Human {
                 public static void main(String[] args)
                 throws Exception {
                  try {
                   try {
                    throw new Sneeze();
                   } catch ( Annoyance a ) {
                    System.out.println("Caught Annoyance");
                    throw a;
                   }
                  } catch ( Sneeze s ) {
                   System.out.println("Caught Sneeze");
                   return ;
                  } finally {
                   System.out.println("Hello World!");
                  }
                 }
                }
结果<br>
Caught Annoyance<br>
Caught Sneeze<br>
Hello World!<br>
##### 常见的 RuntimeException 有哪些
ClassCastException(类转换异常)、IndexOutOfBoundsException(数组越界)、NullPointerException(空指针)、ArrayStoreException(数据存储异常，操作数组时类型不一致)、BufferOverflowException异常
##### Java常见异常有哪些
java.lang.IllegalAccessError：违法访问错误。当一个应用试图访问、修改某个类的域（Field）或者调用其方法，但是又违反域或方法的可见性声明，则抛出该异常。<br>
java.lang.InstantiationError：实例化错误。当一个应用试图通过Java的new操作符构造一个抽象类或者接口时抛出该异常.<br>
java.lang.OutOfMemoryError：内存不足错误。当可用内存不足以让Java虚拟机分配给一个对象时抛出该错误。<br>
java.lang.StackOverflowError：堆栈溢出错误。当一个应用递归调用的层次太深而导致堆栈溢出或者陷入死循环时抛出该错误。<br>
java.lang.ClassCastException：类造型异常。假设有类A和B（A不是B的父类或子类），O是A的实例，那么当强制将O构造为类B的实例时抛出该异常。该异常经常被称为强制类型转换异常。<br>
java.lang.ClassNotFoundException：找不到类异常。当应用试图根据字符串形式的类名构造类，而在遍历CLASSPAH之后找不到对应名称的class文件时，抛出该异常。<br>
java.lang.ArithmeticException：算术条件异常。譬如：整数除零等。<br>
java.lang.ArrayIndexOutOfBoundsException：数组索引越界异常。当对数组的索引值为负数或大于等于数组大小时抛出。<br>
java.lang.IndexOutOfBoundsException：索引越界异常。当访问某个序列的索引值小于0或大于等于序列大小时，抛出该异常。<br>
java.lang.InstantiationException：实例化异常。当试图通过newInstance()方法创建某个类的实例，而该类是一个抽象类或接口时，抛出该异常。<br>
java.lang.NoSuchFieldException：属性不存在异常。当访问某个类的不存在的属性时抛出该异常。<br>
java.lang.NoSuchMethodException：方法不存在异常。当访问某个类的不存在的方法时抛出该异常。<br>
java.lang.NullPointerException：空指针异常。当应用试图在要求使用对象的地方使用了null时，抛出该异常。譬如：调用null对象的实例方法、访问null对象的属性、计算null对象的长度、使用throw语句抛出null等等。<br>
java.lang.NumberFormatException：数字格式异常。当试图将一个String转换为指定的数字类型，而该字符串确不满足数字类型要求的格式时，抛出该异常。<br>
java.lang.StringIndexOutOfBoundsException：字符串索引越界异常。当使用索引值访问某个字符串中的字符，而该索引值小于0或大于等于序列大小时，抛出该异常。《LeetCode刷题Java版答案》<br>
在 Java 中处理异常并不是一个简单的事情。不仅仅初学者很难理解，即使一些有经验的开发者也需要花费很多时间来思考如何处理异常，包括需要处理哪些异常，怎样处理等等。这也是绝大多数开发团队都会制定一些规则来规范进行异常处理的原因。而团队之间的这些规范往往是截然不同的。

##### 在 finally 块中清理资源或者使用 try-with-resource 语句
当使用类似InputStream这种需要使用后关闭的资源时，一个常见的错误就是在try块的最后关闭资源。

                public void doNotCloseResourceInTry() {
                    FileInputStream inputStream = null;
                    try {
                        File file = new File("./tmp.txt");
                        inputStream = new FileInputStream(file);
                        // use the inputStream to read a file
                        // do NOT do this
                        inputStream.close();
                    } catch (FileNotFoundException e) {
                        log.error(e);
                    } catch (IOException e) {
                        log.error(e);
                    }
                }
没有异常抛出的时候，这段代码可以正常工作。在执行try 代码块最后部分之前发生了异常，然后停止了，然后没有关闭资源。所以啊，应该把清理工作的代码放到 finally 里去。

##### 使用 finally 代码块
与前面几行 try 代码块不同，finally 代码块总是会被执行。不管 try 代码块成功执行之后还是你在 catch 代码块中处理完异常后都会执行。因此，你可以确保你清理了所有打开的资源。

                public void closeResourceInFinally() {
                    FileInputStream inputStream = null;
                    try {
                        File file = new File("./tmp.txt");
                        inputStream = new FileInputStream(file);
                        // use the inputStream to read a file
                    } catch (FileNotFoundException e) {
                        log.error(e);
                    } finally {
                        if (inputStream != null) {
                            try {
                                inputStream.close();
                            } catch (IOException e) {
                                log.error(e);
                            }
                        }
                    }
                }

##### 优先明确的异常
总是尝试寻找最适合你的异常事件的类，例如，抛出一个 NumberFormatException 来替换一个 IllegalArgumentException 。避免抛出一个不明确的异常。

        public void doNotDoThis() throws Exception {
            ...
        }
        public void doThis() throws NumberFormatException {
            ...
        }

##### 使用描述性消息抛出异常
在抛出异常时，需要尽可能精确地描述问题和相关信息，这样无论是打印到日志中还是在监控工具中，都能够更容易被人阅读，从而可以更好地定位具体错误信息、错误的严重程度等。<br>
但这里并不是说要对错误信息长篇大论，因为本来 Exception 的类名就能够反映错误的原因，因此只需要用一到两句话描述即可。<br>
如果抛出一个特定的异常，它的类名很可能已经描述了这种错误。所以，你不需要提供很多额外的信息。一个很好的例子是 NumberFormatException 。当你以错误的格式提供 String 时，它将被 java.lang.Long 类的构造函数抛出。<br>

        try {
            new Long("xyz");
        } catch (NumberFormatException e) {
            log.error(e);
        }
##### 优先捕获最具体的异常
第一个 catch 块处理所有 NumberFormatException 异常，第二个处理所有非 NumberFormatException 异常的IllegalArgumentException 异常。

                public void catchMostSpecificExceptionFirst() {
                    try {
                        doSomething("A message");
                    } catch (NumberFormatException e) {
                        log.error(e);
                    } catch (IllegalArgumentException e) {
                        log.error(e)
                    }
                }
##### 不要捕获 Throwable 类
Throwable 是所有异常和错误的超类。你可以在 catch 子句中使用它，但是你永远不应该这样做！<br>
如果在 catch 子句中使用 Throwable ，它不仅会捕获所有异常，也将捕获所有的错误。JVM 抛出错误，指出不应该由应用程序处理的严重问题。典型的例子是 OutOfMemoryError 或者 StackOverflowError 。两者都是由应用程序控制之外的情况引起的，无法处理。<br>
所以，最好不要捕获 Throwable ，除非你确定自己处于一种特殊的情况下能够处理错误。<br>

                public void doNotCatchThrowable() {
                    try {
                        // do something
                    } catch (Throwable t) {
                        // don't do this!
                    }
                }
##### 不要忽略异常
很多时候，开发者很有自信不会抛出异常，因此写了一个catch块，但是没有做任何处理或者记录日志。

                public void doNotIgnoreExceptions() {
                    try {
                        // do something
                    } catch (NumberFormatException e) {
                        // this will never happen
                    }
                }
但现实是经常会出现无法预料的异常，或者无法确定这里的代码未来是不是会改动(删除了阻止异常抛出的代码)，而此时由于异常被捕获，使得无法拿到足够的错误信息来定位问题。
合理的做法是至少要记录异常的信息。

                public void logAnException() {
                    try {
                        // do something
                    } catch (NumberFormatException e) {
                        log.error("This should never happen: " + e);
                    }
                }
##### 不要记录并抛出异常
这可能是本文中最常被忽略的最佳实践。可以发现很多代码甚至类库中都会有捕获异常、记录日志并再次抛出的逻辑。如下：

                try {
                    new Long("xyz");
                } catch (NumberFormatException e) {
                    log.error(e);
                    throw e;
                }
这个处理逻辑看着是合理的。但这经常会给同一个异常输出多条日志。如下：

                17:44:28,945 ERROR TestExceptionHandling:65 - java.lang.NumberFormatException: For input string: "xyz"
                Exception in thread "main" java.lang.NumberFormatException: For input string: "xyz"
                at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
                at java.lang.Long.parseLong(Long.java:589)
                at java.lang.Long.(Long.java:965)
                at com.stackify.example.TestExceptionHandling.logAndThrowException(TestExceptionHandling.java:63)
                at com.stackify.example.TestExceptionHandling.main(TestExceptionHandling.java:58)
                如上所示，后面的日志也没有附加更有用的信息。如果想要提供更加有用的信息，那么可以将异常包装为自定义异常。

                public void wrapException(String input) throws MyBusinessException {
                    try {
                        // do something
                    } catch (NumberFormatException e) {
                        throw new MyBusinessException("A message that describes the error.", e);
                    }
                }
因此，仅仅当想要处理异常时才去捕获，否则只需要在方法签名中声明让调用者去处理。

##### 包装异常时不要抛弃原始的异常
捕获标准异常并包装为自定义异常是一个很常见的做法。这样可以添加更为具体的异常信息并能够做针对的异常处理。

在你这样做时，请确保将原始异常设置为原因（注：参考下方代码 NumberFormatException e 中的原始异常 e ）。Exception 类提供了特殊的构造函数方法，它接受一个 Throwable 作为参数。否则，你将会丢失堆栈跟踪和原始异常的消息，这将会使分析导致异常的异常事件变得困难。

                public void wrapException(String input) throws MyBusinessException {
                    try {
                        // do something
                    } catch (NumberFormatException e) {
                        throw new MyBusinessException("A message that describes the error.", e);
                    }
                }
##### 不要使用异常控制程序的流程
不应该使用异常控制应用的执行流程，例如，本应该使用if语句进行条件判断的情况下，你却使用异常处理，这是非常不好的习惯，会严重影响应用的性能。

##### 使用标准异常
如果使用内建的异常可以解决问题，就不要定义自己的异常。Java API 提供了上百种针对不同情况的异常类型，在开发中首先尽可能使用 Java API 提供的异常，如果标准的异常不能满足你的要求，这时候创建自己的定制异常。尽可能得使用标准异常有利于新加入的开发者看懂项目代码。

##### 异常会影响性能
异常处理的性能成本非常高，每个 Java 程序员在开发时都应牢记这句话。创建一个异常非常慢，抛出一个异常又会消耗1~5ms，当一个异常在应用的多个层级之间传递时，会拖累整个应用的性能。<br>

仅在异常情况下使用异常；<br>
在可恢复的异常情况下使用异常；<br>
尽管使用异常有利于 Java 开发，但是在应用中最好不要捕获太多的调用栈，因为在很多情况下都不需要打印调用栈就知道哪里出错了。因此，异常消息应该提供恰到好处的信息。<br>
##### 总结
综上所述，当你抛出或捕获异常的时候，有很多不同的情况需要考虑，而且大部分事情都是为了改善代码的可读性或者 API 的可用性。<br>
异常不仅仅是一个错误控制机制，也是一个通信媒介。因此，为了和同事更好的合作，一个团队必须要制定出一个最佳实践和规则，只有这样，团队成员才能理解这些通用概念，同时在工作中使用它。
异常处理-阿里巴巴Java开发手册 【强制】Java 类库中定义的可以通过预检查方式规避的RuntimeException异常不应该通过catch 的方式来处理，比如：NullPointerException，IndexOutOfBoundsException等等。说明：无法通过预检查的异常除外，比如，在解析字符串形式的数字时，可能存在数字格式错误，不得不通过catch NumberFormatException来实现。正例：if (obj != null) {…} 反例：try { obj.method(); } catch (NullPointerException e) {…}<br>

【强制】异常不要用来做流程控制，条件控制。说明：异常设计的初衷是解决程序运行中的各种意外情况，且异常的处理效率比条件判断方式要低很多。<br>

【强制】catch时请分清稳定代码和非稳定代码，稳定代码指的是无论如何不会出错的代码。对于非稳定代码的catch尽可能进行区分异常类型，再做对应的异常处理。说明：对大段代码进行try-catch，使程序无法根据不同的异常做出正确的应激反应，也不利于定位问题，这是一种不负责任的表现。正例：用户注册的场景中，如果用户输入非法字符，或用户名称已存在，或用户输入密码过于简单，在程序上作出分门别类的判断，并提示给用户。<br>

【强制】捕获异常是为了处理它，不要捕获了却什么都不处理而抛弃之，如果不想处理它，请将该异常抛给它的调用者。最外层的业务使用者，必须处理异常，将其转化为用户可以理解的内容。<br>

【强制】有try块放到了事务代码中，catch异常后，如果需要回滚事务，一定要注意手动回滚事务。<br>

【强制】finally块必须对资源对象、流对象进行关闭，有异常也要做try-catch。说明：如果JDK7及以上，可以使用try-with-resources方式。<br>

【强制】不要在finally块中使用return。说明：try块中的return语句执行成功后，并不马上返回，而是继续执行finally块中的语句，如果此处存在return语句，则在此直接返回，无情丢弃掉try块中的返回点。<br>反例：

                private int x = 0;
                public int checkReturn() {
                    try {
                        // x等于1，此处不返回
                        return ++x;
                    } finally {
                        // 返回的结果是2
                        return ++x;
                    }
                }
【强制】捕获异常与抛异常，必须是完全匹配，或者捕获异常是抛异常的父类。说明：如果预期对方抛的是绣球，实际接到的是铅球，就会产生意外情况。<br>

【强制】在调用RPC、二方包、或动态生成类的相关方法时，捕捉异常必须使用Throwable类来进行拦截。说明：通过反射机制来调用方法，如果找不到方法，抛出NoSuchMethodException。什么情况会抛出<NoSuchMethodError呢？二方包在类冲突时，仲裁机制可能导致引入非预期的版本使类的方法签名不匹配，或者在字节码修改框架（比如：ASM）动态创建或修改类时，修改了相应的方法签名。这些情况，即使代码编译期是正确的，但在代码运行期时，会抛出NoSuchMethodError。<br>

【推荐】方法的返回值可以为null，不强制返回空集合，或者空对象等，必须添加注释充分说明什么情况下会返回null值。说明：本手册明确防止NPE是调用者的责任。即使被调用方法返回空集合或者空对象，对调用者来说，也并非高枕无忧，必须考虑到远程调用失败、序列化失败、运行时异常等场景返回null的情况。<br>

【推荐】防止NPE，是程序员的基本修养，注意NPE产生的场景：1） 返回类型为基本数据类型，return包装数据类型的对象时，自动拆箱有可能产生NPE。反例：public int f() { return Integer对象}， 如果为null，自动解箱抛NPE。2） 数据库的查询结果可能为null。3） 集合里的元素即使isNotEmpty，取出的数据元素也可能为null。4） 远程调用返回对象时，一律要求进行空指针判断，防止NPE。5） 对于Session中获取的数据，建议进行NPE检查，避免空指针。6） 级联调用obj.getA().getB().getC()；一连串调用，易产生NPE。正例：使用JDK8的Optional类来防止NPE问题。<br>

【推荐】定义时区分unchecked / checked 异常，避免直接抛出new RuntimeException()，更不允许抛出Exception或者Throwable，应使用有业务含义的自定义异常。推荐业界已定义过的自定义异常，如：DAOException / ServiceException等。<br>

【参考】对于公司外的http/api开放接口必须使用“错误码”；而应用内部推荐异常抛出；跨应用间RPC调用优先考虑使用Result方式，封装isSuccess()方法、“错误码”、“错误简短信息”。说明：关于RPC方法返回方式使用Result方式的理由：1）使用抛异常返回方式，调用方如果没有捕获到就会产生运行时错误。2）如果不加栈信息，只是new自定义异常，加入自己的理解的error message，对于调用端解决问题的帮助不会太多。如果加了栈信息，在频繁调用出错的情况下，数据序列化和传输的性能损耗也是问题。<br>

【参考】避免出现重复的代码（Don’t Repeat Yourself），即DRY原则。说明：随意复制和粘贴代码，必然会导致代码的重复，在以后需要修改时，需要修改所有的副本，容易遗漏。必要时抽取共性方法，或者抽象公共类，甚至是组件化。正例：一个类中有多个public方法，都需要进行数行相同的参数校验操作，这个时候请抽取：private boolean checkParam(DTO dto) {…}<br>
